name: Deploy to Staging

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
    name: Deploy to WPEngine staging.
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo test

      - name: Download the deploy artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: deploy_artifacts
          path: _build
      - name: Display structure of downloaded files
        run: ls -la _build
