name: Test and deploy
on:
  push:
    branches:
      - main
      - action-deploys

jobs:
  deploy:
    name: Test and deploy to WPEngine staging environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Add HTTP basic auth credentials
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}
        if: env.COMPOSER_AUTH != null
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/web/auth.json

      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: 'web'

      - name: Manually install rollup dependencies (see https://github.com/npm/cli/issues/4828#issuecomment-2404560937)
        run: npm i @rollup/rollup-linux-x64-gnu

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test JavaScript
        run: npm run lint:js

      - name: Test PHP
        run: npm run lint:php

      - name: Check bundlesize
        run: npm run test:bundlesize

      - name: List things
        run: |
          ls -la

      - name: SFTP Upload
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: buildersmozil1.sftp.wpengine.com
          username: buildersmozil1-nick-braica
          password: ${{ secrets.WPENGINE_SFTP_PASSWORD }}
          port: 2222
          uploads: |
            ./web/wp-content/themes/mozilla-builders/ => /wp-content/themes/mozilla-builders
            ./web/wp-content/plugins/ => /wp-content/plugins/
          ignore: |
            ./web/wp-content/themes/mozilla-builders/node_modules

      # # deploy theme
      # - name: GitHub Action Deploy Theme to WP Engine
      #   uses: wpengine/github-action-wpe-site-deploy@v3
      #   with:
      #     WPE_SSHG_KEY_PRIVATE: ${{ secrets.SSH_KEY }}
      #     WPE_ENV: mitadvkitdev
      #     # Deploy Options
      #     SRC_PATH: "themes/mit-advancement-toolkit/"
      #     REMOTE_PATH: "wp-content/themes/mit-advancement-toolkit/"
      #     PHP_LINT: FALSE
      #     FLAGS: -azvr --inplace --delete --exclude=".*"  --exclude=wp-content/mu-plugins/local-plugin --exclude-from=.deployignore
      #     CACHE_CLEAR: TRUE

      # # deploy plugins
      # - name: GitHub Action Deploy Plugins to WP Engine
      #   uses: wpengine/github-action-wpe-site-deploy@v3
      #   with:
      #     WPE_SSHG_KEY_PRIVATE: ${{ secrets.SSH_KEY }}
      #     WPE_ENV: mitadvkitdev
      #     # Deploy Options
      #     SRC_PATH: "plugins/"
      #     REMOTE_PATH: "wp-content/plugins/"
      #     PHP_LINT: FALSE
      #     FLAGS: -azvr --inplace --exclude=".*"  --exclude=wp-content/mu-plugins/local-plugin
      #     CACHE_CLEAR: TRUE
