name: Deploy to Staging
on:
  push:
    branches:
      - main
      - deployment
  workflow_run:
    workflows: ['test']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
    name: Deploy to WPEngine staging.
    runs-on: ubuntu-latest
    steps:
      - name: Download the deploy artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: deploy-artifacts
          path: _build
      - name: Display structure of downloaded files
        run: ls -la _build
